<?php
// generated by Poedit from waterwoo-pdf.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'en','pot-creation-date'=>'2025-07-26 10:52-0700','po-revision-date'=>'2025-07-26 10:52-0700','translation-revision-date'=>'2025-07-26 10:52-0700','project-id-version'=>'PDF Ink Lite','x-generator'=>'Poedit 3.6','messages'=>[]];
